#!/usr/bin/env python

import sys
from argparse import ArgumentParser

from src.patchouli import Patchouli

class Runner:
    def __init__(self):
        self.parser = ArgumentParser(description="Patchouli Plugin Manager", usage='''git patchy [help|show]

    help    Prints help
    show    Prints plugin information and various metadata about them.
                Currently prints plugin name, jar path, folder path if exists, and config file list if exists
''')
        self.parser.add_argument("command", help="Subcommand to run: 'git patchy [help|show]'")

        if len(sys.argv)==1:
            self.parser.print_help(sys.stderr)
            sys.exit(1)

        self.args = self.parser.parse_args(sys.argv[1:2])

        if not hasattr(self, self.args.command):
            print('Unrecognized subcommand')
            self.parser.print_help()
            sys.exit(1)

        getattr(self, self.args.command)()

    def gen_base_subcommand_argparser(self) -> ArgumentParser:
        parser = ArgumentParser()
        parser.add_argument('--env', default=None)
        return parser

    def help(self):
        self.parser.print_help()

    def show(self):
        parser = self.gen_base_subcommand_argparser()
        args = parser.parse_args(sys.argv[2:])

        print(args)
        patchy = Patchouli(target_env=args.env)
        patchy.run()

if __name__ == "__main__":
    runner = Runner()
