# The base path of the server environment data
base_path: "/var/lib/yukkuricraft/"
# The default env to run git-patchy commands as
default_env: "prod"
# The default target env to copy data to when using `git patchy copy-to`
default_copy_to_env: "dev1"
# If any directory does not yet exist for a given env - such as its env folder, plugins folder, etc - create the directory by default.
# If set to 'false', tool will error out if any needed directory does not exist.
default_create_missing_dirs: true

# Regex validating env names. PCRE mostly works, but it's put through Python's regex engine.
# Case sensitive. Careful of the anchors.
# Default: ^(?:vcs|prod|dev\d+)$ allows envs: vcs, prod, and dev# where # is any int
env_name_regex: ^(?:vcs|prod|dev\d+)$

# The user:group that should own the files on disk at base_path
mc_data_user: minecraft
mc_data_group: minecraft

# Plugin configs
plugins:
  # Path to the plugin folder on the filesystem after base_path/$env/
  relpath_from_env_root: "plugins"

  # Folders in the plugins folder to ignore
  folders_to_ignore:
    - Updater
    - archive
    - bStats

  # Configuration for finding config files
  configs:
    # Default list of suffixes to look for in all plugin folders
    suffixes:
      - .yml
      - .yaml
      - .conf
      - .lang
      - .txt

    # Use this if you need to add or rem suffixes for specific plugins
    # All "add" paths are evaluated first. Then the "rem" paths are evaluated. Patchouli will
    #   remove paths evaluated as part of the "add" if there are any overlaps.
    suffixes_override:
      LuckPerms: # This example will load json files as configs from the root of the plugindir, but explicitly exclude json files under json-storage/users.
        add:
          - suffix: .json
            path: .
        rem:
          - suffix: .json
            path: json-storage/users # We don't really make changes to user json. Rely on backups.
      GriefDefender:
        add:
          - suffix: .json
            path: .
        rem:
          - suffix: .conf
            path: old_worlds

    # Subpaths of plugin folders to ignore.
    paths_to_ignore:
      ChatFeelings:
        # Eg, ignore 'plugins/ChatFeelings/Data'
        # Paths may be multiple levels deep, eg Data/smth/else
        - Data
      Essentials:
        - userdata
      GriefDefender:
        - lib
      InventoryRollback:
        - saves
      InventoryRollbackPlus:
        - backups
      LibsDisguises:
        - SavedSkins
        - SavedDisguises
      LuckPerms:
        - libs
      OnTime:
        - reports
      PerWorldInventory:
        - data
        - tmp_bak
      WorldEdit:
        - .archive_unpack
        - sessions
      dynmap:
        - web
        - templates
        - renderdata
        - export
